config/routes.rb
Rails.application.routes.draw do
  get 'wuyun/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'


  resources :users do
    member do
      get :following, :followers, :active
      match :active, to: :active, via: [:post, :patch]
      match :unactive, to: :unactive, via: [:post, :patch]
    end
  end


    get '/clearw', to: 'clears#new'
    post '/clearw', to: 'clears#create'
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    #resources :albums
    #resources
    resources :photos,          only: [:new, :create, :destroy]

    post '/upload', to: 'upload#create'
    post '/uploads_finish', to: 'upload#finish'
    delete '/delete_uploads', to: 'upload#destroy'

    resources :products

    resources :upcs
    resources :kwords
    resources :xstockplans
    resources :xstocks
    resources :etemplates
    resources :amatemps
    resources :amagroups
    resources :inoutplans
    resources :inoutstocks
    resources :inventories
    resources :warehouses
    resources :wuyuns

    resources :xstockplans do
      member do
        match :importexcel, to: :importexcel, via: [:post, :patch]
        match :exportexcel, to: :exportexcel, via: [:post, :patch]
      end
    end

    resources :inoutplans do
      member do
        match :importexcel, to: :importexcel, via: [:post, :patch]
        match :exportexcel, to: :exportexcel, via: [:post, :patch]
      end
    end

    resources :albums do
      post 'outexcel',action: :outexcel, on: :collection
      post 'download',action: :download_excel, on: :collection
    end

    resources :photos do
      delete :destroy_multiple, action: :destroy, on: :collection
    end

end

app/models/amagroup.rb
class Amagroup < ApplicationRecord
  belongs_to :user
  has_many :amatemps
  has_many :amagroupwithas, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 }
  validates :user_id, presence: true

  has_many :amatemps, through: :amagroupwithas, source: :amatemp

end

app/controllers/amagroups_controller.rb
class AmagroupsController < ApplicationController
  before_action :logged_in_user
  include ApplicationHelper
  def new
    @amagroup = Amagroup.new
    @amatemps=user_amatemps
  end

  def create
    @amagroup = current_user.amagroups.build(amagroup_params)
    if @amagroup.save
      add_amagrouptwitha   @amagroup
      set_current_used @amagroup,current_user.amagroups
      flash[:success] = "Amagroup created"
      redirect_to amagroups_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

    @amagroup = Amagroup.find(params[:id])

  end

  def edit
    @amagroup = Amagroup.find(params[:id])
    @amatemps=user_amatemps
  end

  def destroy
    Amagroup.find(params[:id]).destroy
    flash[:success] = "Amagroup deleted"
    redirect_to amagroups_path
  end

  def update
    @amagroup = Amagroup.find(params[:id])
    # ss= params.require(:amatemp)["sport_type1"]
    # flash[:success] = ss
    # redirect_to amagroups_path

    if @amagroup.update(amagroup_params)
      add_amagrouptwitha   @amagroup
      set_current_used @amagroup,current_user.amagroups
      flash[:success] = "amagroup updated"
      redirect_to amagroups_path
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  #end update

  def index
    @amagroups = current_user.amagroups.order(isused: :desc).order(created_at: :desc).paginate(page: params[:page])
  end

  #add add_amatwitha
   def add_amagrouptwitha agroup
     user_amatemps.each do |ama|
       valueid = params.require(:amatemp)[ama.id.to_s]
       amagroupwith= agroup.amagroupwithas.where("amatemp_id =? ",ama.id)
       if valueid==ama.id.to_s
          if(amagroupwith.count==0)
            amagroupwith = Amagroupwitha.new
            amagroupwith.amagroup= agroup
            amagroupwith.amatemp = ama
            amagroupwith.save
          end
       else
         if(amagroupwith.count>0)
           amagroupwith= amagroupwith.first
           amagroupwith.destroy
         end
       end

     end
   end



  private
    def amagroup_params
      params.require(:amagroup).permit(:name, :remark, :isused)
    end

    def user_amatemps
      current_user.amatemps.where("isused")
    end
end

app/helpers/amagroups_helper.rb
module AmagroupsHelper

  # get Amagroupwitha value
    def getamagcheck(amatemp,amagroup)
      amawith = amagroup.amagroupwithas.where('amatemp_id=?',amatemp.id)
      if(amawith.count>0)
        return true
      else
        return false
      end
    end


end

app/views/amagroups/_form.html.erb
<%= form_with model: @amagroup,class: "row g-2" do |f| %>
<%= render 'shared/error_messages', object: f.object %>

<div class="">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>
<div class="">
  <%= f.label :remark %>
  <%= f.text_area :remark, class: 'form-control',rows: 6,placeholder: "remark" %>
</div>

<div class="">
  <%= f.check_box :isused ,class: "form-check-input"%>
  <%= f.label :isused,"是否当前使用(表示相册编辑导出使用该组)" ,class: "form-check-label"%>

</div>
<div class="row mt-3">
  <label for="">请选择需要添加到组的属性</label>
</div>
<div class="row my-2 ">
  <% @amatemps.each_with_index do |amatemp,num|%>
    <% if(num%3==0) %>
    </div>
    <div class="row my-2 ">
    <%end%>
    <div class="col-4">
      <%= check_box_tag("amatemp["+amatemp.id.to_s+"]",amatemp.id,getamagcheck(amatemp,@amagroup)) %>
      <%s =(amatemp.amagroups.map {|mapag| mapag.name}).join(',')%>
      <%s = s.blank? ? "" : "("+s+")"%>
      <%= label_tag (amatemp.name+s) %>
        </div>
      <%end%>
    </div>
<br/>
<div class="col-auto">
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
</div>

<% end %>

app/views/amagroups/edit.html.erb
<% provide(:title, "Edit Amagroup") %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/etemplate_menu' %>
  </aside>
  <div class="col-md-9">
    <div class="col-md-9 col-md-offset-1">
 <h1>Edit Amagroups</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/amagroups/index.html.erb
<% provide(:title, 'My Amagroups') %>

  <div class="row">
    <aside class="col-md-3 albums_menu">
      <%= render 'shared/etemplate_menu' %>
    </aside>
    <div class="col-md-9">

      <div class="row templates">
        <table class="table">
          <thead>
            <tr>
              <th scope="col" class="col-sm-2">Name</th>
              <th scope="col" class="col-sm-6">包含属性</th>
              <th scope="col" class="col-sm-2" >当前使用</th>
              <th scope="col" class="col-sm-2">操作</th>

            </tr>
          </thead>

          <% @amagroups.each do |ob| %>
            <tr>
              <td >
                <%= link_to ob.name, ob %>

              </td>
              <td >
                <p style="width:500px;word-wrap:break-word;"><%= (ob.amatemps.map{|mapap| mapap.name }).join(",") %></p>
              </td>
              <td >
                <%= ob.isused %>
              </td>
              <td >
                <%= link_to "edit",edit_amagroup_path(ob) %>
                ｜
                <%= link_to "delete", ob, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

              </td>

            </tr>

          <% end %>

        </table>
      </div>

      <%= will_paginate %>
    </div>

  </div>

app/views/amagroups/new.html.erb
<% provide(:title, 'New Amagroups') %>
<% provide(:button_text, 'Create my amagroup') %>
<div class="row" >
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/etemplate_menu' %>
  </aside>
  <div class="col-md-9">

    <div class="col-sm-10">
     <h1>Create Amagroup</h1>
      <%= render 'form' %>
    </div>

  </div>

</div>

app/views/amagroups/show.html.erb
<% provide(:title, "Show Amagroup") %>

  <div class="row">
    <aside class="col-md-3 albums_menu">
      <%= render 'shared/etemplate_menu' %>
    </aside>
    <div class="col-md-9">
      <section class="etemplate_info">
        <h5><%=@amagroup.name%></h5>
        <textarea class="form-control" rows="6" name="reamrk" id="reamrk"><%=@amagroup.remark %></textarea>
        <span><%= link_to "edit",edit_amagroup_path(@amagroup) %>
          |
          <%= link_to "delete", @amagroup, method: :delete, data: { confirm: "You sure?"} %></span>
      </section>

      <div>