config/routes.rb
Rails.application.routes.draw do
  get 'wuyun/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'


  resources :users do
    member do
      get :following, :followers, :active
      match :active, to: :active, via: [:post, :patch]
      match :unactive, to: :unactive, via: [:post, :patch]
    end
  end


    get '/clearw', to: 'clears#new'
    post '/clearw', to: 'clears#create'
    resources :account_activations, only: [:edit]
    resources :password_resets, only: [:new, :create, :edit, :update]
    resources :microposts,          only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
    #resources :albums
    #resources
    resources :photos,          only: [:new, :create, :destroy]

    post '/upload', to: 'upload#create'
    post '/uploads_finish', to: 'upload#finish'
    delete '/delete_uploads', to: 'upload#destroy'

    resources :products

    resources :upcs
    resources :kwords
    resources :xstockplans
    resources :xstocks
    resources :etemplates
    resources :amatemps
    resources :amagroups
    resources :inoutplans
    resources :inoutstocks
    resources :inventories
    resources :warehouses
    resources :wuyuns

    resources :xstockplans do
      member do
        match :importexcel, to: :importexcel, via: [:post, :patch]
        match :exportexcel, to: :exportexcel, via: [:post, :patch]
      end
    end

    resources :inoutplans do
      member do
        match :importexcel, to: :importexcel, via: [:post, :patch]
        match :exportexcel, to: :exportexcel, via: [:post, :patch]
      end
    end

    resources :albums do
      post 'outexcel',action: :outexcel, on: :collection
      post 'download',action: :download_excel, on: :collection
    end

    resources :photos do
      delete :destroy_multiple, action: :destroy, on: :collection
    end

end

app/models/inoutplan.rb
class Inoutplan < ApplicationRecord
  belongs_to :user
   belongs_to :warehouse
  has_many :inoutstocks, dependent: :destroy
  validates :name, presence: true, length: { maximum: 50 },
            uniqueness: { case_sensitive: false }
end

app/controllers/inoutplans_controller.rb
class InoutplansController < ApplicationController
  before_action :logged_in_user
  require "spreadsheet"
  include InoutplansHelper

  Spreadsheet.client_encoding = "UTF-8"

  def new
    @inoutplan = Inoutplan.new
  end



  def index
    @inoutplans = current_warehourse.inoutplans.order(created_at: :desc).paginate(page: params[:page])
  end

  def destroy
    #出库
    @inoutplan = Inoutplan.find(params[:id])
    out_stock(@inoutplan,current_warehourse)
    @inoutplan.destroy
    flash[:success] = "Inout plan deleted"
    redirect_to inoutplans_path
  end

  def edit
    @inoutplan = Inoutplan.find(params[:id])
  end

  def update
    @inoutplan =  Inoutplan.find(params[:id])
    #out_stock(@inoutplan,current_warehours)
    out_stock_str(@inoutplan.inout,current_warehourse,@inoutplan.presku.to_s)
    @inoutplan.inoutstocks.each do |d|
      d.delete
    end

    if @inoutplan.update(inoutplan_params)


      inouts=inoutplan_params["inout"]
      presku=inoutplan_params["presku"]
      str = twoarray_for_plan(inouts,presku)

      str.each_with_index do |f,n|
        p = @inoutplan.inoutstocks.find_by(sku: f[0].upcase)
        if p.nil?
          p = Inoutstock.new
          p.normal= 0
          p.defect= 0
          p.sizeup= 0
          p.sizedown= 0
        end

        f.each_with_index do |e,m|
          if(m==0)
             p.sku = e.upcase
           elsif(m==1)
             p.normal= e
           elsif(m==2)
             p.defect= e
           elsif(m==3)
             p.sizeup= e
           elsif(m==4)
             p.sizedown= e
          end
        end

        p.inoutplan_id = @inoutplan.id
        p.save
      end


      in_stock_str(inouts,current_warehourse,presku)
      #in_stock(@inoutplan,current_warehourse)
      #in_stock(@inoutplan,current_warehourse)
      #flash[:success] = inouts.to_s
      flash[:success] = "Inout plan updated"
      redirect_to inoutplans_path

    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def show
    @inoutplan = Inoutplan.find(params[:id])
    #@xstocks =Xstock.where("xstockplan_id="+params[:id])
    @inoutstocks = @inoutplan.inoutstocks
  end


  def importexcel
    @inoutplan = Inoutplan.find(params[:id])
    #删除之前记录
    out_stock_str(@inoutplan.inout,current_warehourse,@inoutplan.presku)
    uploader = ExcelUploader.new
    uploader.store!(params[:inoutplan][:excelfile])
    path= File.join Rails.root, 'public/'
    book = Spreadsheet.open (path+ "#{uploader.store_path}")
    sheet1 = book.worksheet 0

    sheet1.each 1  do |row|
      p= Inoutstock.find_by(sku: row[0])
      if p.nil?
        p = Inoutstock.new
      end
      p.inoutplan_id = @inoutplan.id
      p.sku = row[0]
      p.normal=row[1].to_i
      p.defect = row[2].to_i
      p.sizeup = row[3].to_i
      p.sizedown = row[4].to_i
      p.actived = row[5]


      p.save

    end
    #入库
    set_inout(@inoutplan)

    in_stock_str(@inoutplan.inout,current_warehourse,@inoutplan.presku)

    flash[:success] = "Instocks import!"
    redirect_to inoutplan_path(@inoutplan)

  end

  def exportexcel
    @inoutplan = Inoutplan.find(params[:id])
    # add format
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name =  @inoutplan.name

    format = Spreadsheet::Format.new :size => 11,
                                     :vertical_align => :middle,
                                     :border => :thin,
                                     :pattern_fg_color => :yellow,
                                     :pattern => 1

    sheet1.row(0).default_format = format
    sheet1.row(0).height = 30
    sheet1.column(0).width =15
    title = %w(SKU Normal Defect Sizeup Sizedown Actived)
    title.each_with_index do |n,index|
      sheet1[0,index] = n
    end

    @inoutstocks = @inoutplan.inoutstocks

    @inoutstocks.each_with_index do |ob,index|

      sheet1[index+1,0]= ob.sku
      sheet1[index+1,1]= ob.normal
      sheet1[index+1,2]= ob.defect
      sheet1[index+1,3]= ob.sizeup
      sheet1[index+1,4]= ob.sizedown
      sheet1[index+1,5]= ob.actived


    end




    path= File.join Rails.root, 'public/'

    #create excel
    filename = @inoutplan.name+".xls";

    file_path=path+"uploads/export/"+filename

    if File.exist?(file_path)
      File.delete(file_path)
    end
    book.write(file_path)
    File.open(file_path, 'r') do |f|
      send_data f.read.force_encoding('BINARY'), :filename => filename, :type => "application/xls", :disposition => "inline"
    end

  end

  def create
    @inoutplan = Inoutplan.new(inoutplan_params)
    @inoutplan.user =current_user
    @inoutplan.warehouse = current_warehourse


    if @inoutplan.save

      str = twoarray_for_plan(inoutplan_params["inout"],inoutplan_params["presku"])
      str.each_with_index do |f,n|
        p = Inoutstock.new
        p.normal= 0
        p.defect= 0
        p.sizeup= 0
        p.sizedown= 0

        f.each_with_index do |e,m|
          if(m==0)
             p.sku = e.upcase
           elsif(m==1)
             p.normal= e
           elsif(m==2)
             p.defect= e
           elsif(m==3)
             p.sizeup= e
           elsif(m==4)
             p.sizedown= e
          end

        end
        p.inoutplan_id = @inoutplan.id
        p.save

      end

      #in_stock(@inoutplan,current_warehourse)
      in_stock_str(inoutplan_params["inout"],current_warehourse,inoutplan_params["presku"])
      flash[:success] = "stock plan created!"
      redirect_to inoutplans_path

    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

    def inoutplan_params
      params.require(:inoutplan).permit(:name, :presku, :inout, :actived)
    end


end

app/helpers/inoutplans_helper.rb
module InoutplansHelper
  BGCOLORS = ['#553D32','#CC0000', '#EB9500','#EDEAE6','#006DCD']
  
  
  def random_color(num)
    
   BGCOLORS.sample(num)
  end
  
  def twoarray_for_plan(inoutstr,presku)    
    ob = inoutstr.tr("\n","|").split('|')
    result = Array.new
    ob.each_with_index do |f,n|
      pref= presku.upcase + f
      result[n]= pref.split(' ')
      
    end
    return result
  end
  
  def current_warehourse
    ob = current_user.warehouses.where(is_current: true).first
    if ob==nil
      ob= current_user.warehouses.first
      if ob==nil
        set_default_warehouse
      end

      ob.is_current =true
      ob.save
    end
    return ob
  end
  
  #set 
  def set_inout(plan)
    inoutstocks= plan.inoutstocks
   
    str=""
    inoutstocks.each_with_index do |f,n|
      
      str += f.sku.upcase
      str += " "
      str += f.normal.to_s 
      str += " "
      str += f.defect.to_s
      str += " "
      str += f.sizeup.to_s
      str += " "
      str += f.sizedown.to_s
      
      
      str+="\r\n"
    end
    plan.inout = str
    plan.presku =''
    plan.save
    
    
  end
  
  #设置默认仓库
  def set_default_warehouse()
    re = Warehouse.first
    if re.nil?
       re = Warehouse.new
       re.name="默认仓库"
       re.address=""
       re.isused = true
       re.is_current =true
       re.user_id = current_user.id
       re.save     
    end
    re
  end
  
  
  def out_stock(plan,warehouse)
    inoutstocks= plan.inoutstocks
    
    inoutstocks.each_with_index do |f,n|
      
      p = warehouse.inventories.find_by(sku: f.sku)
      if p.nil?
       
      else
        
        p.normal -= f.normal 
        p.defect -= f.defect
        p.sizeup -= f.sizeup
        p.sizedown -= f.sizedown
        p.save
      end
    
      
      
    end
  end
  
 
  
  def out_stock_str(inout,warehouse,presku)
    str = twoarray_for_plan(inout,presku)
    
    str.each_with_index do |f,n|
      p = warehouse.inventories.find_by(sku: f[0].upcase)
      if p.nil?
        
      else
        
      f.each_with_index do |e,m|
        if(m==0)
           p.sku = e.upcase
         elsif(m==1)
           p.normal -= e.to_i
         elsif(m==2)
           p.defect -= e.to_i
         elsif(m==3)
           p.sizeup -= e.to_i
         elsif(m==4)
           p.sizedown -= e.to_i
         end
       end
      
      p.warehouse_id= warehouse.id 
      p.save
      end
    end
  end
  
  # 根据文本入库
  def in_stock_str(inout,warehouse,presku)
    str = twoarray_for_plan(inout,presku)
    
    str.each_with_index do |f,n|
      p = warehouse.inventories.find_by(sku: f[0].upcase)
      #不存在 则新建
      if p.nil?
        p = Inventory.new   
        p.normal=0
        p.defect=0
        p.sizeup=0
        p.sizedown=0
        
        parentsku = get_parentsku f[0].upcase
        p.parentsku = parentsku
        p.name = get_name(parentsku)
        
        p.user_id = current_user.id
        f.each_with_index do |e,m|
          if(m==0)
             p.sku = e.upcase
           elsif(m==1)
             p.normal = e.to_i
           elsif(m==2)
             p.defect = e.to_i
           elsif(m==3)
             p.sizeup = e.to_i
           elsif(m==4)
             p.sizedown = e.to_i
          end
        end
        
      else
        f.each_with_index do |e,m|
          if(m==0)
             p.sku = e.upcase
           elsif(m==1)
             p.normal += e.to_i
           elsif(m==2)
             p.defect += e.to_i
           elsif(m==3)
             p.sizeup += e.to_i
           elsif(m==4)
             p.sizedown += e.to_i
          end
        end
      end
      
      
      
      p.warehouse_id= warehouse.id 
      p.save
    end
  end
#出库入库
  def in_stock(plan,warehouse)
    inoutstocks= plan.inoutstocks
    
    inoutstocks.each_with_index do |f,n|
      
     p = warehouse.inventories.find_by(sku: f.sku)
      if p.nil?
        p = Inventory.new
        p.sku = f.sku.upcase
        p.normal= f.normal
        p.defect = f.defect
        p.sizeup = f.sizeup
        p.sizedown = f.sizedown
        
        parentsku = get_parentsku f.sku
        p.parentsku = parentsku
        p.name = get_name(parentsku)
        p.user_id = current_user.id
        p.warehouse_id= warehouse.id
      else
        
        p.normal += f.normal 
        p.defect += f.defect
        p.sizeup += f.sizeup
        p.sizedown += f.sizedown
        
      end
      p.save
      
      
    end
  end
  
  def get_parentsku(sku)
    sku.upcase.match(/[A-Z]+[0-9]+/).to_s
  end
  
  def get_name(parentsku)
    parentsku.upcase.match(/[0-9]+/).to_s
  end
  
end

app/views/inoutplans/_form.html.erb
<%= form_for(@inoutplan,html: {class: "row g-2"}) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
	<%=f.text_field :presku, class: 'form-control', placeholder: "prefix sku,ex:XDMPT001"%>
	<%= f.text_area :inout, class: 'form-control',rows: 6,placeholder: "ex:DB-xl 10 2 3 1" %>
	<p><%= f.label :actived %><%= f.check_box :actived %>  </p>

    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
 <% end %>

app/views/inoutplans/edit.html.erb
<% provide(:title, "Edit inout plan") %>
<% provide(:button_text, 'Save changes') %>
<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/xstock_menu' %>
  </aside>
  <div class="col-md-9">
    <div class="col-md-9 col-md-offset-1">
 <h1>Edit stock plan</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/inoutplans/index.html.erb
<% provide(:title, '出库入库') %>

  <div class="row">
    <aside class="col-md-3 albums_menu">
      <%= render 'shared/xstock_menu' %>
    </aside>
    <div class="col-md-9">

      <div class="row ">
        <h5>
          出入库记录</h5>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Actived</th>
              <th scope="col">Date</th>
                <th scope="col">Options</th>
            </tr>
          </thead>
          <% @inoutplans.each do |ob| %>
            <tr>
              <td>
                <%= link_to ob.name, ob %>

              </td>
              <td>
                <%= ob.actived==true ? "√":"×"%>
              </td>
              <td><%= time_ago_in_words(ob.created_at) %>
                ago.</td>
              <td>
                <p>
                  <%= link_to "edit",edit_inoutplan_path(ob) %>
                  |
                  <%= link_to "delete", ob, method: :delete, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"} %>
                </p>
              </td>
            </tr>

          <% end %>

        </table>
      </div>

      <%= will_paginate %>
    </div>

  </div>

app/views/inoutplans/new.html.erb
<% provide(:title, '新增出入库') %>
<% provide(:button_text, '创建出入库') %>
<div class="row" >
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/xstock_menu' %>
  </aside>
  <div class="col-md-9">

    <div class="col-md-6 col-md-offset-2">
     <h1>Create 出入库</h1>
      <%= render 'form' %>
    </div>

  </div>

</div>

app/views/inoutplans/show.html.erb
<% provide(:title, "出库入库") %>

<div class="row">
  <aside class="col-md-3 albums_menu">
   <%= render 'shared/xstock_menu' %>
  </aside>
  <div class="col-md-9">
	 
	  
    <section class="album_info">
      <span><%=@inoutplan.name%></span>


<span><%= link_to "edit",edit_inoutplan_path(@inoutplan) %> | <%= link_to "delete", @inoutplan, method: :delete, data: { confirm: "You sure?"} %></span>
    </section>
    <div class=" ">
		 
      <table class="table">
        <tr>
          <th>SKU</th>

          <th>Total</th>
          <th>Normal</th>
          <th>Defact</th>
          <th>Sizeup</th>
          <th>Sizedown</th>
          <th>Options</th>
          </tr>
		 
      <% @inoutstocks.each do |ob| %>
      <tr>
        <td> <%=  ob.sku %>  </td>

        <td> <%=  ob.normal + ob.defect + ob.sizeup+ ob.sizedown%>  </td>
        <td> <%=  ob.normal %>  </td>
        <td> <%=  ob.defect %>  </td>
		<td> <%=  ob.sizeup %>  </td>
		<td> <%=  ob.sizedown %>  </td>
       

         <td>
           <%= link_to "delete", ob, method: :delete, data: { confirm: "You sure?"} %>
         </td>
         </tr>
       <% end %>

  </table>
  </div>


    <div class="row">
         <%= form_for(@inoutplan,url: { action: "importexcel" }, html: { multipart: true }) do |f| %>
      <div class="col-md-6">
        <%= f.file_field "excelfile", class: 'form-control' %>
        </div>
           <div class="col-md-3">
            <%= f.submit "ImportExcel",:class => "btn btn-large btn-primary" %>
   </div>
           <% end %>
              </div>
  <div class="col-md-3">
       <%=form_for @inoutplan, url: { action: "exportexcel" }  do |f| %>
     <%= f.submit "ExportExcel",:class => "btn btn-large btn-primary" %>
     <% end %>
      </div>